// 09-29-react-router-switch/src/components/items/multiple-pic/index.js
/**
 * @file entry file
 * @author yuanxin
 */

import React, {Component} from 'react';
import {itemFy, clickAble} from '../decorators';
import style from './style.css';

@itemFy(true)
export default class MultiplePic extends Component {

	static classes = 'multiple-pic';

	render() {

		const {title, imageList} = this.props.data;

		const imageComponents = imageList.map(image => (<img src={image} />));

		return (<React.Fragment>
				<h3>{title}</h3>
				{imageComponents}
			</React.Fragment>);
	}
}

// 08-17/src/components/multiple-pic.vue
<template>
  <div class="item multiple-image">
    <h3>
      {{item.data.title}}
    </h3>
    <div class="image-list">
      <img 
        v-for="(image, idx) in item.data.imageList" :key="idx" 
        v-bind:src="image" 
      />
    </div>
  </div>
</template>

<script>
export default {
  props: ['item']
}
</script>
