// 08-18/src/components/single-pic.vue
<template>
  <div class="item single-pic">
    <div class="content">
      <span>
        {{title}}
      </span>
    </div>
    <img v-bind:src="imgUrl" />
  </div>
</template>

<script>
export default {
  props: ['title', 'imageList'],
  computed: {
    imgUrl() {
      return this.imageList[0];
    }
  }
}
</script>

// 09-29-react-router-switch/src/components/items/single-pic/index.js
/**
 * @file entry file
 * @author yuanxin
 */
import React, {Component} from 'react';
import {itemFy} from '../decorators';
import style from './style.css';

@itemFy(true)
export default class SinglePic extends Component {

	static classes = 'single-pic';

	render() {
		const {title, imageList} = this.props.data;

		return (<React.Fragment>
				<h3>{title}</h3>
				<img src={imageList[0]} />
			</React.Fragment>);
	}
}
